apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
  name: eip-sample-pool
spec:
  address: 192.168.0.91-192.168.0.100
  protocol: layer2
  interface: eth0
  disable: false
status:
  occupied: false
  usage: 1
  poolSize: 10
  used: 
    "192.168.0.91": "default/test-svc"
  firstIP: 192.168.0.91
  lastIP: 192.168.0.100
  ready: true
  v4: true